### PR TITLE
Add unity cloud build support.

### PR DESCRIPTION
**Pull request by Neuxz**
Add support for [developer.cloud.unity3d.com](developer.cloud.unity3d.com)

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
This looks great! Can you modify your brace style to match the rest of the project? (starting brace on same line instead of new line)

**Comment by Jawnnypoo** [comment]
I'll go ahead and do this locally. Thanks!

**Comment by Neuxz** [comment]
Did glich.com pull the changes automaticly and need a few hours or is there an other step i forgot to do?

**Comment by Jawnnypoo** [comment]
Yeah sorry, I needed to import the changes. Live now!

**Pull request merged**
