### PR TITLE
Provider class system / async functions

### PR DESCRIPTION
**Pull request by Mythen96**
This pullrequest is a system overhaul.
All providers are now class based and are extending the new added BaseProvider Util class(Thanks to #1 for the idea. #1 can be closed now).
It is an easier way for handling providers and their data.
Also added with this pullrequest are async functions that allows us to get information from external urls as example (Needed in #28)

I also added the package "request-promise-native" as dependency.
Basic usage of this package:
```js
const rp = require('request-promise-native');

let response = await rp.get('http://example.com/');
//everything down here will executed when the request above is finished. 
//response will be directly the body response of the requested url.
```

The node engine was changed from 6.9.x to 8.1.x as 6.9.x does not support async and await.

### CODE REVIEW

**Comment by dscalzi** [comment]
I like the system! One thing though, it might be benefitial to add JSDocs.

**Comment by Mythen96** [comment]
I will do that after my gaming session

**Comment by Mythen96** [comment]
Just looked at JSDocs. As i'm not realy familiar with it and don't think that it is realy necessary to have JSDocs for every file here.
What I came up with is that the only file that needs a documentation is the BaseProvider.js. For that i would do some examples how to use it in a Wiki page here on GitHub but unfortunately it is not possible to create a pullrequest for wiki pages

**Comment by Mythen96** [comment]
So i just did some wiki pages as i would do it on my repository.
Examples for creating a new providers: 
https://github.com/IsekaiDevForks/skyhook/wiki/Creating-a-new-Provider

and a small documentation of the DiscordPayload class: 
https://github.com/IsekaiDevForks/skyhook/wiki/util%5CDiscordPayload

i dont think that any other file need any explanation right now.

**Comment by Jawnnypoo** [comment]
Awesome work @Mythen96 ! Had a few questions if you have some time to answer them. Also, I would totally love to include the instructions on creating a new provider, I think it would be just fine to have it as something like `PROVIDERS.md` or something in the repo, with a link to the instructions from the README. Reason I am hesitant to have it as a wiki is the exact reason you mentioned, since contributors cannot make pull requests on wikis.

**Comment by Mythen96** [comment]
Added them in a sub directory called docs.
Feel free to write to me on discord :)

**Pull request merged**
