### PR TITLE
minor improvements / message layout change of gitlab push event

### PR DESCRIPTION
**Pull request by Mythen96**
Hey, i realy like your service you are running here.
I just changed some things

- moved the providers to an own folder for better handling
- added the mising ";" wherever it was missing
i know it's not needed but i realy like it better and my IDE was giving me warnings about it :laughing:
- change the layout of the message in the GitLab push event
i changed the layout at the base of the layout that Discord gives their GitHub push events.
Look of the layout: http://puu.sh/vioDa/4e290635bf.png

maybe you will change the layout of the other messages too. If not i will do it if i got the time for it :)

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Hey there, appreciate this, can you resolve the merge conflicts, then I will pull this in. Thanks a bunch!

**Comment by Mythen96** [comment]
Hey that should resolve the conflicts. Sorry for the useless commits there my IDE was being a little bit dumb and created some sort of mess for me. but it all works :)

**Comment by Neuxz** [comment]
I've just realized you override all changes i made in [986ccf2d7eecf466956ab92b762db6fae34c93a1](https://github.com/Commit451/skyhook/commit/986ccf2d7eecf466956ab92b762db6fae34c93a1)

**Comment by Mythen96** [comment]
Hey @Neuxz,
i override the changes you made in the gitlab.js yes. Thats because i made the layout of the message the same as discord is doing with the github webhook.
The other changes of you i didn't even touched except adding the ";" to every line where it was missing.

**Comment by Neuxz** [comment]
The Problem is that you forked skyhook before i commited my changes in gitlab. So that my changes like commit details are now overwritten.

**Comment by Mythen96** [comment]
Das ist richtig das ich den pullrequest erstellt habe während deiner auch noch offen war. Allerdings habe ich dann auf bitten von Jawnnypoo nachdem er deinen gemerged hatte die änderungen gezogen und dann erst meine änderungen wieder drauf gemacht. Daher sollte der Unity Support etc trotzdem mit drin sein wie man an den hinteren commits von mir noch sieht. Ich habe halt nur das layout der Nachricht für das GitLab Push event umgeschrieben. Ansonsten wüsste ich grade nicht welche auf welche Änderungen du sonst noch hinweisen möchtest sorry.

**Comment by Neuxz** [comment]
Ich habe die beiden wichtigsten Punkte mal zur review geschrieben.

**Comment by Mythen96** [comment]
Macht ja nichts, ich bin immer froh wenn mich jemand auf irgendwas hinweist wo es ggf. Probleme gibt :)
Wo finde ich denn die review? Sehe die zurzeit nicht.

**Comment by Neuxz** [comment]
Unter files changed findest du die reviews

**Comment by Jawnnypoo** [comment]
So, whats the status here? I think @Mythen96 should be able to just rebase/merge in master and it should be mostly fine?

**Comment by Mythen96** [comment]
komisch, mir wird da kein review angezeigt o.O

**Comment by Neuxz** [comment]
Yea i'll change the Icon loader later back. So i think you can pull it in.

**Comment by Neuxz** [comment]
Oben unter files changed in der gitlab.js

**Pull request merged**
