### PR TITLE
#96: Adds support for github anonymous users

### PR DESCRIPTION
**Pull request by Lugghawk**
- Not sure the best way to deal with the avatar. I found a link to the bitbucket anonymous one which I just hardcoded in. It works but that image may disappear.
- Added a new test for the issue also.
- Original bitbucket test is missing the `await` on the promise also, but was passing when I added it.

I'm not sure of the chances of it happening but if someone uses the username `Anonymous` on github this might lessen skyhook's functionality for them. If you want extra confidence you could also do a check for `this.body.actor.links` being undefined.

### CODE REVIEW

**Comment by dscalzi** [comment]
Maybe do the second check you mentioned. I can imagine there being more than a few people with the Anon username.

**Comment by Lugghawk** [comment]
Can do. I thought usernames on bb needed to be unique though.

**Comment by Jawnnypoo** [comment]
According to issue https://github.com/Commit451/skyhook/issues/96 `links` can be undefined. Instead of checking `if (author.name === 'Anonymous' && this.body.actor.links === undefined) {` you can probably just check if (this.body.actor.links === undefined) {` to know if the user is undefined or not, right?

**Comment by Lugghawk** [comment]
I believe so. I did this mostly because I was unaware of the full spectrum of possibilities from bitbucket. I can refine it but I'm not sure whether there are other cases where links are undefined. A private profile maybe?

**Comment by Jawnnypoo** [comment]
Yep, that could be the case too. Or someone just hasn't set up their profile in git. I think just checking `this.body.actor.links === undefined` should be good though.

**Comment by dscalzi** [comment]
I typically use `whatever == null` but I guess `whatever === undefined` should work.

**Comment by Lugghawk** [comment]
OK then. Anything else? Need me to squish or something?

**Comment by Jawnnypoo** [comment]
Looks good, thanks!

**Pull request merged**
