### PR TITLE
New Provider: Confluence

### PR DESCRIPTION
**Pull request by SG004**
Initial Confluence Provider Implementation. I wanted this functionality for a project of mine, and so when I saw that the project was open source, I was ecstatic that I could help add functionality to your awesome software.

There are a few missing features, and I spent the better half of an evening working on this, let me know if this initial implementation is enough for an initial submission or if I need to add things.

### CODE REVIEW

**Review by dscalzi — CHANGES_REQUESTED** [review]
Please lint the project

**Comment by SG004** [comment]
> Please lint the project

I am unfamiliar with what you mean by lint. What do you mean lint?

**Comment by SG004** [comment]
nvm googled it

**Comment by dscalzi** [comment]
Run `npm run lint` and fix the style violations

**Comment by SG004** [comment]
Ran npm run lint on the following scripts (There were no violations)

- .\src\index.ts
- .\src\provider\Confluence.ts
- .\test\confluence\confluence-spec.ts

image

**Comment by Jawnnypoo** [comment]
Thanks for contributing!

**Pull request merged**
