### PR TITLE
Added a space between the commit hash and message.

### PR DESCRIPTION
**Pull request by dscalzi**
This will probably make it look a little better.

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
@Mythen96 This isn't going to mess up the character count elsewhere is it?

**Comment by dscalzi** [comment]
Only character count that could be messed up is the 256 limit. See that here https://github.com/Commit451/skyhook/pull/25/commits/ab764face74216d356c6e38ab1f062d80c677508#diff-186771fedc9a0c2c7360bc32aaf73c92L36

If that's actually a hard limit I can add another commit decrementing it to 255.

**Comment by Jawnnypoo** [comment]
Ahh, good point, thanks!

**Comment by Mythen96** [comment]
There is no problem with the character count as fields can have a value up to 1024 characters. i just put the limit to 256 to prevent getting over the global character limit. So there is no problem here.

**Pull request merged**
