### PR TITLE
Initial support of BitBucket

### PR DESCRIPTION
**Pull request by Mythen96**
Started to create the support of BitBucket as wished in #7 
Current supported events:

### Repository events
- repo:push ([Message layout preview](https://puu.sh/vm85t/8079ad9dba.png))
- repo:fork ([Message layout preview](https://puu.sh/vmbp7/87c7f8635f.png))
- repo:updated ([Message layout preview](https://puu.sh/vmcr5/6cc8ee2032.png))
- repo:commit_comment_created ([Message layout preview](https://puu.sh/vmZbc/2f388ba41e.png))
- repo:commit_status_created ([Message layout preview](https://puu.sh/vn0EX/5261ae5d1c.png))
- repo:commit_status_updated ([Message layout preview](https://puu.sh/vn0Ft/d7b0023aa7.png))

### Issue events
- issue:created ([Message layout preview](https://puu.sh/vn1FG/75b471b149.png))
- issue:updated ([Message layout preview](https://puu.sh/vn1Hh/f40b3d2fe4.png))
- issue:comment_created ([Message layout preview](https://puu.sh/vn1HV/4d4558ba5e.png))

### Pull request events
- pullrequest:created ([Message layout preview](https://puu.sh/vn2pe/0358f32bf3.png))
- pullrequest:updated ([Message layout preview](https://puu.sh/vn39P/c2601483df.png))
- pullrequest:approved ([Message layout preview](https://puu.sh/vndx0/032da023e8.png))
- pullrequest:unapproved ([Message layout preview](https://puu.sh/vndxp/83e9291d34.png))
- pullrequest:fulfilled ([Message layout preview](https://puu.sh/vndxT/2f8314a6da.png))
- pullrequest:rejected ([Message layout preview](https://puu.sh/vndyA/8799b19c09.png))
- pullrequest:comment_created ([Message layout preview](https://puu.sh/vndPf/8f28e769df.png))
- pullrequest:comment_updated (cant show atm as this event only gets fired when some time passed between creating/last edit of the comment)
- pullrequest:comment_deleted ([Message layout preview](https://puu.sh/vndSG/c9422fc268.png))

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Nice stuff! Is this ready for pulling in, or are there more events to add?

**Comment by Mythen96** [comment]
As i got the time for it i added the missing events :)
Feel free to pull it

**Comment by Jawnnypoo** [comment]
@Mythen96 Would love to, but looks like the build failed :(
https://travis-ci.org/Commit451/skyhook/builds/222836072

**Comment by Mythen96** [comment]
yea sorry, should be fixed now :)

**Comment by Jawnnypoo** [comment]
Great stuff, thanks!

**Pull request merged**
